### ISSUE TITLE
Client GUI checklist

### ISSUE THREAD

**Issue by rafelafrance** [rafelafrance/digi_leap#37]
Still to do:
- [x] Add help text to fields
- [x] Save images
- [x] Save text
- [x] Improve error reporting
- [x] Add spinners
- [x] Improve control states (enable/disable/reset)
- [x] Improve design
- [x] Show label image on index change
- [x] Finish draw label logic
- [x] Handle resizes
- [x] CSS break points
- [x] Add label view

Maybe add undo controls?
